- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- shell:
  # Create local files if they're not already created
  - type nul >> gitconfig_local
  - type nul >> shell_local
  - type nul >> ssh/config_local

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/completions: fish/completions
    ~/.config/fish/conf.d: fish/conf.d
    ~/.config/fish/functions: fish/functions
    ~/.config/starship.toml: starship.toml
    ~/.gitconfig:
    ~/.gitconfig_local:
    ~/.gitignore_global:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.shell:
    ~/.shell_local:
    ~/.ssh/config: ssh/config
    ~/.ssh/config_local: ssh/config_local
    # Windows-specific links
    ~/Documents/PowerShell/profile.ps1: powershell/profile.ps1
    ~/vimfiles: vim
    ~/_vimrc: vimrc

- create:
  - ~/.vim/undodir

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - >
    git clean -fdx
    vim/pack/vendor/start
    zshrc/plugins
