- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- shell:
  # Create local files if they're not already created
  - touch gitconfig_local
  - touch shell_local
  - touch ssh/config_local

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/completions: fish/completions
    ~/.config/fish/conf.d: fish/conf.d
    ~/.config/fish/functions: fish/functions
    ~/.config/nvim: nvim
    ~/.config/ruff/ruff.toml: ruff.toml
    ~/.config/starship.toml: starship.toml
    ~/.editrc:
    ~/.inputrc:
    ~/.gitconfig:
    ~/.gitconfig_local:
    ~/.gitignore_global:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.pythonrc:
    ~/.shell:
    ~/.shell_local:
    ~/.ssh/config: ssh/config
    ~/.ssh/config_local: ssh/config_local
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc: 
    ~/.zsh:
    ~/.zshrc:

- create:
  - ~/.vim/undodir

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - >
    git clean -fdx
    vim/pack/vendor/start
    zshrc/plugins
