- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- shell:
    # Create local files if they're not already created
    - touch gitconfig.local
    - touch shell.local.sh
    - touch shell.local.fish
    - touch starship.local.toml
    - touch ssh/config.local

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/completions: fish/completions
    ~/.config/fish/conf.d: fish/conf.d
    ~/.config/fish/functions: fish/functions
    ~/.config/nvim: nvim
    ~/.config/ruff/ruff.toml: ruff.toml
    ~/.config/starship.toml: starship.toml
    ~/.config/starship.local.toml: starship.local.toml
    ~/.editrc:
    ~/.inputrc:
    ~/.gitconfig:
    ~/.gitconfig.local: gitconfig.local
    ~/.gitignore_global:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.pythonrc:
    ~/.shell:
    ~/.shell.local.sh: shell.local.sh
    ~/.shell.local.fish: shell.local.fish
    ~/.ssh/config: ssh/config
    ~/.ssh/config.local: ssh/config.local
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- create:
    - ~/.vim/undodir

- shell:
    - >
      git clean -fdx
      vim/pack/vendor/start
      zsh/plugins
